Repository pycontribs/zuul-lint, pull requests merged in 2023-10, with the labels that each got.

#7 Add contructor for secrets
  .pre-commit-config.yaml
  tests/data/zuul-config-valid.yaml
  zuul_lint/__main__.py
  zuul_lint/zuul-schema.json
Labels: bug

#12 Initial GHA workflows
  .github/workflows/release.yml
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog

#11 Update project packaging
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/test_zuul_lint.py
  tox.ini
  zuul_lint/__init__.py
  zuul_lint/__main__.py
  zuul_lint/version.py
Labels: bug

#10 feat: Update schema to latest Zuul version
  zuul_lint/zuul-schema.json
Labels: feature
